### ISSUE TITLE
Support destroy endpoints

### ISSUE THREAD

**Issue by ryandoherty** [RealScout/contactually-rb#3]
It would be great if the contactually-rb gem supported deleting objects. The API does support this: https://developers.contactually.com/docs/v2/#contacts-delete-delete

**Comment by ncavig** [comment]
Agreed! It's curious that the API returns the deleted object in the response, I suppose that could cause problems down the line if we instantiate, for instance, a `contact` object that doesn't exist remotely because we just deleted it. Perhaps that brings up a use case for something like ActiveRecord's `#persisted?` or `#new_record?` methods and implement something like a `#deleted?` flag to prevent nested resource calls. This may save us in the future too if we decide that `#save` or `#update` methods should exist on updatable objects.

I digress, we should support deletes 👍

**Comment by nickblumenthal** [comment]
👍 agreed!
